kind: pipeline
name: drone

#base path first clone file to this path
workspace:
  base: /opt
  path: src/first_project

steps:
  #second to build the project when use java, go or so, other project like python, node will not need this step
  - name: build
    image: golang:1.12
    commands:
      - cd src
      - go build
   # scp the build binary file to remote server
  - name: scp
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      user:
        from_secret: ssh_user
      port: 22
      password:
        from_secret: ssh_password
      target:
        /home/tomcat/drone
      source:
        ./src/game-server

    #publish the docker images to docker registry, which need a Dockerfile in the root path first
  - name: publish
    image: plugins/docker
    settings:
      repo: slowmoon/first-example
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
    #ssh to the host machine and then  docker pull the images and run
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      user:
        from_secret: ssh_user
      port: 22
      password:
         from_secret: ssh_password
      script:
        - docker run  --rm  slowmoon/first-example:latest
