kind: pipeline
name: drone

workspace:
  base: /opt
  path: src/first-project

steps:
  - name: build
    image: golang:1.12
    environment:
      - GOPATH=/go:/opt/src/first-project
    commands:
      - go build
      - ./game-server
