kind: pipeline
name: drone

workspace:
  base: /opt
  path: src/first_project

steps:
  - name: build
    image: golang:1.12
    commands:
      - cd src
      - go build


  - name: publish-docker
    image: plugins/docker
    settings:
      repo: slowmoon/first-example
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true


  - name: scp
    image: appleboy/drone-scp
    settings:
      host: 35.220.222.205
      user: tomcat
      port: 22
      password:
        from_secret: ssh_password
      target:
        /home/tomcat/drone
      source:
        ./src/game-server

