workspace:
  base: /go
  path: src/first-project/src


pipeline:
  build:
    image: golang:1.12
    commands:
      - pwd
      - go env
      - go version
      - go build

  publish:
    image: plugins/docker
    registry: https://index.docker.io/v1/
    repo: slowmoon/first-example
    secrets: [ slowmoon, along665 ]
    tags:
      - latest
