kind: pipeline
name: drone

workspace:
  base: /opt
  path: src/first_project

steps:
  - name: build
    image: golang:1.12
    commands:
      - cd src
      - go build

  - name: scp
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      user:
        from_secret: ssh_user
      port: 22
      password:
        from_secret: ssh_password
      target:
        /home/tomcat/drone
      source:
        ./src/game-server
    #need a Dockerfile in the root path
  - name: publish
    image: plugins/docker
    settings:
      repo: slowmoon/first-example
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
    #ssh to the host machine and then  docker pull the images and run
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      user:
        from_secret: ssh_user
      port: 22
      password:
         from_secret: ssh_password
      script:
        - docker run  slowmoon/first-example:latest
