kind: pipeline
name: drone

workspace:
  base: /opt
  path: src/first_project

steps:
  - name: build
    image: golang:1.12
    environment:
      GOPATH: /opt/src/first_project:/go
    commands:
      - export GOPATH=$GOPATH
      - go build 
      - ./game-server
