kind: pipeline
name: drone

workspace:
  base: /opt
  path: src/first-project

steps:
  - name: build
    image: golang:1.12
    commands:
      - pwd
      - go env
      - go version
      - go build
